version: "3"

services:
  web-srv:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./nginx/config.template:/config.template
      - ./nginx/cert.crt:/etc/nginx/cert.crt
      - ./nginx/cert.key:/etc/nginx/cert.key
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    command:  ["/app/entrypoint.sh"]